### ISSUE TITLE
Docker for Windows issue

### ISSUE THREAD

**Issue by SerialDev** [JAremko/docker-x11-bridge#1]
I want to try this with docker emacs: 
to test it out I did
`docker run -d  --name x11-bridge  -e MODE="tcp"  -e XPRA_HTML="yes"  -e DISPLAY=:14  -e XPRA_PASSWORD=111  -p 10000:10000  jare/x11-bridge`

It yields this error: 

`C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from dae                                     mon: driver failed programming external connectivity on endpoint x11-bridge (3d4                                     49c0dd0ac352697be8eac41dca44d9425967b76c0130e6ef8fe4c1f5337ce): Error starting u                                     serland proxy: mkdir /port/tcp:0.0.0.0:10000:tcp:172.17.0.2:10000: input/output                                      error.
`

**Comment by JAremko** [comment]
@SerialDev  that seems like a Docker issue https://github.com/docker/for-win/issues/573
