### ISSUE TITLE
Display :14 unavailable, simulating -nw

### ISSUE THREAD

**Issue by sergeiudris** [JAremko/docker-x11-bridge#5]
hi, when running 

```shell
  docker run -d \
  --name x11-bridge \
  -e MODE="tcp" \
  -e XPRA_HTML="yes" \
  -e DISPLAY=:14 \
  -p 10000:10000 \
  jare/x11-bridge

  docker run -d \
  --name emacs-1 \
  --volumes-from x11-bridge \
  -e DISPLAY=:14 \
  jare/emacs emacs
```
emacs fails:

```shell
$ docker logs --tail 10 emacs-1
No protocol specified
Display :14 unavailable, simulating -nw
emacs: standard input is not a tty
```

```shell
$ docker logs --tail 10 x11-bridge
2018-12-14 02:52:00,561  No module named sound.common
2018-12-14 02:52:00,624 xpra X11 version 2.3.2-r19729 64-bit
2018-12-14 02:52:00,625  uid=1000 (xpra), gid=1000 (xpra)
2018-12-14 02:52:00,625  running with pid 24 on Linux
2018-12-14 02:52:00,625  connected to X11 display :14 with 24 bit colors
2018-12-14 02:52:00,765 xpra is ready.
2018-12-14 02:52:00,991 started command 'xhost +' with pid 52
access control disabled, clients can connect from any host
2018-12-14 02:52:00,993 5.1GB of system memory
2018-12-14 02:52:00,993 child 'xhost +' with pid 52 has terminated
```

what's odd, it worked once (the first time) and i saw editors. now i cant run it gain. 
tried (no success): running 2 editors, removing containers/images, rebooting, updating graphics card driver

environment:

OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.17134 N/A Build 17134

Client: Docker Engine - Community
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        4d60db4
 Built:             Wed Nov  7 00:47:51 2018
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       4d60db4
  Built:            Wed Nov  7 00:55:00 2018
  OS/Arch:          linux/amd64
  Experimental:     true

**edit**

same issue on `ubuntu:18.04` - worked once (the first time) and now
```shell
$ sudo docker logs --tail 10 emacs-1
No protocol specified
Display :14 unavailable, simulating -nw
emacs: standard input is not a tty
```

Distributor ID: Ubuntu
Description:    Ubuntu 18.04.1 LTS
Release:        18.04
Codename:       bionic

Client:
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        4d60db4
 Built:             Wed Nov  7 00:49:01 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       4d60db4
  Built:            Wed Nov  7 00:16:44 2018
  OS/Arch:          linux/amd64
  Experimental:     false

**Comment by JAremko** [comment]
@sergeiudris This is really weird indeed :thinking: 

Mb try with host network:

```
docker run -d \
  --name x11-bridge \
  -e MODE="tcp" \
  -e XPRA_HTML="yes" \
  -e DISPLAY=:14 \
  --net=host \    
  jare/x11-bridge
```

**Comment by sergeiudris** [comment]
@JAremko  
tried `host` network and made sure containers were removed, but,sadly, didn't help
well, i sure its something on my side (otherwise it wouldn't run the first time), will wait for a bright idea
appreciate your help, though!

**Comment by NerdsvilleCEO** [comment]
Oddly enough, I am getting this same issue
